CREATE DATABASE LAB2
GO

USE LAB2
GO

CREATE TABLE DON_VI (
	MA_DV NVARCHAR(15), 
	TEN_DV NVARCHAR(50) NOT NULL, 
	CONSTRAINT PK_MADV PRIMARY KEY (MA_DV)
)

CREATE TABLE NHAN_VIEN (
    MA_NV INT IDENTITY(1, 1),
    HO_TEN NVARCHAR(50) NOT NULL, 
    GIOI_TINH BIT NOT NULL CONSTRAINT DF_GT DEFAULT 1,
    CMND CHAR(9) NOT NULL,
    NGAY_SINH DATE NOT NULL,
    LUONG FLOAT NOT NULL CONSTRAINT CHECK_LUONG CHECK (LUONG > 0),
	MA_DV NVARCHAR(15) NOT NULL,
    CONSTRAINT PK_MANV PRIMARY KEY (MA_NV),
	CONSTRAINT FK_MADV FOREIGN KEY (MA_DV) REFERENCES DON_VI(MA_DV)
);
GO

INSERT INTO DON_VI VALUES
	(N'49.01.CNTT', N'Công nghệ thông tin K49'),
	(N'49.01.SPTIN', N'Sư phạm tin học K49');
GO

INSERT INTO NHAN_VIEN VALUES 
	(N'Nguyễn Ngọc Phú Tỷ', 1, '293847261', '02/20/2005', 3000, N'49.01.CNTT'),
	(N'Nguyễn Lâm Hoàng Dung', 0, '232334347', '11/16/2005', 2000, N'49.01.SPTIN');
GO

SELECT	MA_NV AS N'Mã nhân viên',
		HO_TEN AS N'Họ và tên',

		CASE GIOI_TINH 
		WHEN 1 THEN N'Nam'
		ELSE N'Nữ'
		END AS N'Giới tính',

		CMND, 
		FORMAT(NGAY_SINH, 'dd/MM/yyyy') AS N'Ngày sinh',
		LUONG AS N'Lương',
		MA_DV AS N'Đơn vị'
FROM NHAN_VIEN