CREATE DATABASE LAB1
GO

USE LAB1
GO

CREATE TABLE NHAN_VIEN (
    MA_NV INT IDENTITY(1, 1),
    HO_TEN NVARCHAR(50) NOT NULL, 
    GIOI_TINH BIT NOT NULL CONSTRAINT DF_GT DEFAULT 1,
    CMND CHAR(9) NOT NULL,
    NGAY_SINH DATE NOT NULL,
    LUONG FLOAT NOT NULL CONSTRAINT CHECK_LUONG CHECK (LUONG > 0),
    CONSTRAINT PK_MANV PRIMARY KEY (MA_NV)
);
GO

INSERT INTO NHAN_VIEN VALUES 
	(N'Nguyễn Ngọc Phú Tỷ', 1, '293847261', '02/20/2005', 3000),
	(N'Nguyễn Lâm Hoàng Dung', 0, '232334347', '11/16/2005', 2000);
GO

SELECT	MA_NV AS N'Mã nhân viên',
		HO_TEN AS N'Họ và tên',

		CASE GIOI_TINH 
		WHEN 1 THEN N'Nam'
		ELSE N'Nữ'
		END AS N'Giới tính',

		CMND, 
		FORMAT(NGAY_SINH, 'dd/MM/yyyy') AS N'Ngày sinh',
		LUONG AS N'Lương'
FROM NHAN_VIEN