-- Truy van du lieu
-- Cau 1
SELECT MACT, HOTEN, NGAYSINH, DIACHI, VITRI FROM CAUTHU
JOIN QUOCGIA ON CAUTHU.MAQG = QUOCGIA.MAQG
JOIN CAULACBO ON CAUTHU.MACLB = CAULACBO.MACLB
WHERE CAULACBO.TENCLB = N'SHB Đà Nẵng' AND QUOCGIA.TENQG = N'Bra-xin'

-- Cau 2
SELECT HOTEN FROM CAUTHU
JOIN THAMGIA ON CAUTHU.MACT = THAMGIA.MACT
JOIN TRANDAU ON THAMGIA.MATD = TRANDAU.MATRAN
GROUP BY HOTEN HAVING SUM(SOTRAI) >= 2

-- Cau 3
SELECT MATRAN, NGAYTD, SANVD.TENSAN, CAULACBO1.TENCLB AS TENCLB1, CAULACBO2.TENCLB AS TENCLB2, KETQUA FROM TRANDAU
JOIN SANVD ON TRANDAU.MASAN = SANVD.MASAN
JOIN CAULACBO AS CAULACBO1 ON TRANDAU.MACLB1 = CAULACBO1.MACLB
JOIN CAULACBO AS CAULACBO2 ON TRANDAU.MACLB2 = CAULACBO2.MACLB
WHERE NAM = 2009 AND VONG = 3

-- Cau 4
SELECT HUANLUYENVIEN.MAHLV, TENHLV, NGAYSINH, DIACHI, HLV_CLB.VAITRO, CAULACBO.TENCLB FROM HUANLUYENVIEN
JOIN HLV_CLB ON HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV
JOIN CAULACBO ON HLV_CLB.MACLB = CAULACBO.MACLB
JOIN QUOCGIA ON HUANLUYENVIEN.MAQG = QUOCGIA.MAQG
WHERE QUOCGIA.TENQG = N'Việt Nam'

-- Cau 5
SELECT CAULACBO.MACLB, CAULACBO.TENCLB, SANVD.TENSAN, SANVD.DIACHI, COUNT(CAUTHU.MACT) AS CTNUOCNGOAI FROM CAULACBO
JOIN SANVD ON CAULACBO.MASAN = SANVD.MASAN
JOIN CAUTHU ON CAULACBO.MACLB = CAUTHU.MACLB
WHERE CAUTHU.MAQG <> 'VN'
GROUP BY CAULACBO.MACLB, CAULACBO.TENCLB, SANVD.TENSAN, SANVD.DIACHI
HAVING COUNT(CAUTHU.MACT) > 2

-- Cau 6
SELECT TINH.TENTINH, COUNT(CAUTHU.MACT) AS SOLUONG FROM CAULACBO 
JOIN TINH ON CAULACBO.MATINH = TINH.MATINH
JOIN CAUTHU ON CAULACBO.MACLB = CAUTHU.MACLB
WHERE CAUTHU.VITRI = N'Tiền Đạo' 
GROUP BY TINH.TENTINH 

-- Cau 7


-- Cau 8
SELECT HUANLUYENVIEN.TENHLV FROM HUANLUYENVIEN
JOIN HLV_CLB ON HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV
JOIN CAULACBO ON HLV_CLB.MACLB = CAULACBO.MACLB
WHERE HUANLUYENVIEN.DIENTHOAI IS NULL

-- Cau 9

-- Cau 10

-- Cau 11
